### ISSUE TITLE
Warning: "incomplete final line found"

### ISSUE THREAD

**Issue by bryanvictor** [bryanvictor/BibWrangleR#1]
ProQuest text documents contain a copyright at the end that does not include a carriage return.  This generates a warning after the function has completed.  Need to either include code that corrects for the lack of carriage return or suppress this specific warning message since it will always be produced.

**Comment by beperron** [comment]
Yeah, I had a script in awk or sed that would strip the copyright stuff at the end of the document.  I actually just manually deleted those lines.    

So, I guess pre-processing the proQuest is necessary.  You can add that in the READ.ME file of just deleting the copyright stuff, or offering this as an automation.  You can also probably do this in R, given that a carriage return is specified as \r.  

sed -i '' -e '$a\' file

http://unix.stackexchange.com/questions/31947/how-to-add-a-newline-to-the-end-of-a-file

**Comment by ClaytonJY** [comment]
@beperron careful about the line-endings, as they are OS-specific, e.g. unix-likes use `\n`, Windows uses `\r\n`. R on linux seems to handle either of those just fine, but `\r` is just a carriage return, which then overwrites that line from the beginning:

```
 > cat('what follows is a', '\n', 'newline')
what follows is a 
 newline
> cat('what follows is a', '\r\n', 'newline')
what follows is a 
 newline
> cat('what follows is a', '\r', 'newline')
 newlinelows is a
```

 I think `\n` should work everywhere, though.

Where is the error coming from, the `readlines` call on line 42 of `proquestBWR.R`?

**Comment by bryanvictor** [comment]
Yes, it is coming from the call on line 42.  If I add `warn=FALSE` following `readLines` I suppress the warning.  Any cautions about that suppression?

**Comment by ClaytonJY** [comment]
Not on my end, and much better than using `suppressWarnings`, which was gonna be my suggestion. Didn't know `readLines` had that argument, nifty.

**Comment by bryanvictor** [comment]
Ok, great.
